baseurl = "/"
title = "THAT GUY WITH THE MOHAWK"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[blackfriday]
  hrefTargetBlank = true

[params]
  description = '<h2>jonathan pirro</h2>event photographer, music reviewer, speaker & mc'
  site_title = "that guy with the mohawk | work by j. pirro"
  logoimage = "images/tlg-logo.png"
  copyright = "2018 J. Pirro"
  BackgroundImages = [
    "images/bg/01.jpg",
    "images/bg/02.jpg",
    "images/bg/03.jpg",
    "images/bg/04.jpg",
    "images/bg/05.jpg",
    "images/bg/06.jpg",
    "images/bg/07.jpg",
    "images/bg/08.jpg",
    "images/bg/09.jpg",
    "images/bg/10.jpg",
    "images/bg/11.jpg",
    "images/bg/12.jpg",
    "images/bg/13.jpg",
    "images/bg/14.jpg",
    "images/bg/15.jpg",
    "images/bg/16.jpg",
    "images/bg/17.jpg",
    "images/bg/18.jpg",
    "images/bg/19.jpg",
    "images/bg/20.jpg",
    "images/bg/21.jpg",
    "images/bg/22.jpg",
    "images/bg/23.jpg",
    "images/bg/24.jpg",
    "images/bg/25.jpg",
    "images/bg/26.jpg",
    "images/bg/27.jpg",
    "images/bg/28.jpg",
    "images/bg/29.jpg",
    "images/bg/30.jpg",
    "images/bg/31.jpg",
    "images/bg/32.jpg",
    "images/bg/33.jpg",
    "images/bg/34.jpg",
    "images/bg/35.jpg",
    "images/bg/36.jpg",
    "images/bg/37.jpg",
    "images/bg/38.jpg"
  ]
  BackgroundStyle = "#000000;"
  OpenLinksInNewWindow = true

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/jonthebastard"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://facebook.com/jonmpirro"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/jmpirro"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/jonthebastard"

[[params.social]]
  medium = "vimeo"
  icon = "vimeo"
  link = "https://vimeo.com/obstacle"

[languages]
[languages.en]
languageName = "English"
weight = 1
